language: generic
arch: amd64
os: linux
dist: xenial
services:
  - docker
before_install:
  - docker build -t kirtanbodawala/multi-service-app -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true kirtanbodawala/multi-service-app npm run test
after_success:
  - docker build -t kirtanbodawala/multi-nginx ./nginx
  - docker build -t kirtanbodawala/multi-server ./server
  - docker build -t kirtanbodawala/multi-worker ./worker
  - docker build -t kirtanbodawala/multi-client ./client
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push kirtanbodawala/multi-nginx
  - docker push kirtanbodawala/multi-server
  - docker push kirtanbodawala/multi-worker
  - docker push kirtanbodawala/multi-client
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-647593412039"
  bucket_path: "multi-docker"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master