version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: redis
    restart: always
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    expose:
      - "80"
    ports:
      - "8081:80"
  api:
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DB=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432
  client:
    stdin_open: true
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker/
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
